Repository AY2122S2-CS2103T-T17-1/tp, pull requests merged in 2022-04, with the labels that each got.

#203 Update UG purpose of guide and features
  docs/UserGuide.md
Labels: documentation

#204 Update User Guide to include tips and warnings
  docs/UserGuide.md
Labels: documentation

#205 Update User Guide and Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#250 Fix inconsistent font
  src/main/resources/view/DarkTheme.css
Labels: bug

#251 Fix validity of ReminderDate
  src/main/java/seedu/tinner/model/role/ReminderDate.java
  src/test/java/seedu/tinner/model/role/ReminderDateTest.java
Labels: bug

#252 Update User Guide to fix PED bugs and Invalid ReminderDate Message
  docs/UserGuide.md
  docs/images/ReminderPane.png
  src/main/java/seedu/tinner/model/role/ReminderDate.java
Labels: documentation

#254 Fix bugs
  docs/UserGuide.md
  src/main/java/seedu/tinner/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/tinner/logic/commands/AddRoleCommand.java
  src/main/java/seedu/tinner/logic/commands/EditRoleCommand.java
  src/main/java/seedu/tinner/model/company/CompanyName.java
  src/main/java/seedu/tinner/model/role/ReminderDate.java
  src/main/java/seedu/tinner/model/role/Role.java
  src/main/java/seedu/tinner/model/role/RoleName.java
  src/main/java/seedu/tinner/model/role/Stipend.java
  src/test/java/seedu/tinner/model/company/CompanyNameTest.java
  src/test/java/seedu/tinner/model/company/CompanyTest.java
  src/test/java/seedu/tinner/model/reminder/ReminderTest.java
  src/test/java/seedu/tinner/model/role/RoleNameTest.java
  src/test/java/seedu/tinner/model/role/StipendTest.java
Labels: bug

#256 Updated Project Portfolio Page, minor fixes to User Guide and updated Find Command success message
  docs/UserGuide.md
  docs/team/brendonlau.md
  docs/team/justinyjt.md
  docs/team/kerbysoh.md
  src/main/java/seedu/tinner/logic/commands/FindCommand.java
  src/main/java/seedu/tinner/model/company/CompanyNameContainsKeywordsPredicate.java
  src/main/java/seedu/tinner/model/role/RoleNameContainsKeywordsPredicate.java
  src/test/java/seedu/tinner/logic/commands/FindCommandTest.java
Labels: documentation

#257 Update UG to specify prefixes constraints for add and delete commands
  docs/UserGuide.md
Labels: documentation

#258 Updates UG command format and demo screenshots.
  docs/UserGuide.md
  docs/images/AddCompanyDemo.png
  docs/images/AddRoleDemo.png
  docs/images/DeleteCompanyDemo.png
  docs/images/DeleteRoleDemo.png
  docs/images/remove/Screenshot 2022-04-04 at 12.28.33 PM.png
Labels: documentation

#264 Update command descriptions and UG
  docs/UserGuide.md
  src/main/java/seedu/tinner/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/tinner/logic/commands/AddRoleCommand.java
  src/main/java/seedu/tinner/logic/commands/DeleteCompanyCommand.java
  src/main/java/seedu/tinner/logic/commands/DeleteRoleCommand.java
  src/main/java/seedu/tinner/logic/commands/EditCompanyCommand.java
  src/main/java/seedu/tinner/logic/commands/EditRoleCommand.java
  src/main/java/seedu/tinner/logic/commands/FavouriteCompanyCommand.java
  src/main/java/seedu/tinner/logic/commands/FindCommand.java
  src/main/java/seedu/tinner/logic/commands/HelpCommand.java
  src/main/java/seedu/tinner/logic/commands/SetReminderWindowCommand.java
  src/main/java/seedu/tinner/logic/commands/UnfavouriteCompanyCommand.java
Labels: documentation, enhancement

#263 Update Demo with Find examples
  docs/UserGuide.md
  docs/images/FindCompanyDemo.png
  docs/images/FindRoleDemo.png
Labels: documentation

#261 Update DG edit role implementation, TOC, Manual testing (add,delete,editCompany) and editRole
  docs/DeveloperGuide.md
Labels: documentation

#268 Update User Guide and Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditRoleDiagram.puml
  docs/diagrams/FavouriteActivityDiagram.puml
  docs/diagrams/FavouriteDiagram.puml
  docs/diagrams/FavouriteSequenceDiagram.puml
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/EditRoleDiagram.png
  docs/images/FavouriteActivityDiagram.png
  docs/images/FavouriteDiagram.png
  docs/images/FavouriteSequenceDiagram.png
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
Labels: documentation

#269 Updates DG to include reminder feature and diagrams
  docs/DeveloperGuide.md
  docs/diagrams/CompanyRoleManagerClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ReminderActivityDiagram.puml
  docs/diagrams/ReminderDiagram.puml
  docs/images/CompanyRoleManagerClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ReminderActivityDiagram.png
  docs/images/ReminderDiagram.png
Labels: documentation

#271 Add maximum length enforcement to CompanyName, RoleName and Phone fields
  docs/UserGuide.md
  src/main/java/seedu/tinner/model/company/CompanyName.java
  src/main/java/seedu/tinner/model/company/Phone.java
  src/main/java/seedu/tinner/model/role/RoleName.java
  src/test/java/seedu/tinner/model/company/CompanyNameTest.java
  src/test/java/seedu/tinner/model/company/PhoneTest.java
  src/test/java/seedu/tinner/model/role/RoleNameTest.java
Labels: documentation, enhancement

#267 Update activity diagram for editRole
  docs/DeveloperGuide.md
  docs/diagrams/EditRoleActivityDiagram.puml
  docs/images/EditRoleActivityDiagram.png
Labels: documentation

#276 Update Justin's PPP
  docs/team/justinyjt.md
Labels: documentation

#278 Fix DG "other incorrect test"
  docs/DeveloperGuide.md
Labels: documentation

#277 Update PPP
  docs/team/brendonlau.md
Labels: documentation

#275 Update DG UI component and setWindow
  docs/DeveloperGuide.md
  docs/diagrams/SetReminderWindowActivityDiagram.puml
  docs/diagrams/SetReminderWindowDiagram.puml
  docs/diagrams/SetReminderWindowSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/SetReminderWindowActivityDiagram.png
  docs/images/SetReminderWindowDiagram.png
  docs/images/SetReminderWindowSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#279 Fixes minor errors in DG
  docs/DeveloperGuide.md
  docs/diagrams/ReminderDiagram.puml
  docs/images/ReminderDiagram.png
Labels: documentation

#282 Improve testing, update DG and fix UG bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/tinner/logic/parser/FindCommandParser.java
  src/test/java/seedu/tinner/logic/parser/CompanyListParserTest.java
  src/test/java/seedu/tinner/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/tinner/model/company/UniqueCompanyListTest.java
  src/test/java/seedu/tinner/model/role/UniqueRoleListTest.java
  src/test/java/seedu/tinner/testutil/RoleBuilder.java
  src/test/java/seedu/tinner/testutil/RoleUtil.java
Labels: documentation, testing

#284 Update user stores editRole, editCompany and structure
  docs/DeveloperGuide.md
Labels: documentation

#288 Fix same company name and different spacing
  src/main/java/seedu/tinner/model/company/CompanyName.java
  src/test/java/seedu/tinner/model/company/CompanyNameTest.java
  src/test/java/seedu/tinner/model/company/CompanyTest.java
  src/test/java/seedu/tinner/model/reminder/ReminderTest.java
Labels: bug

#290 Update DG with Add and Delete Role features
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddRoleActivityDiagram.puml
  docs/diagrams/AddRoleSequenceDiagram.puml
  docs/diagrams/DeleteRoleActivityDiagram.puml
  docs/images/AddRoleActivityDiagram.png
  docs/images/AddRoleSequenceDiagram.png
  docs/images/DeleteRoleActivityDiagram.png
Labels: documentation

#289 Fixes Bug and updates DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/tinner/logic/commands/ClearCommand.java
  src/main/java/seedu/tinner/logic/parser/CompanyListParser.java
  src/main/java/seedu/tinner/logic/parser/ParserUtil.java
  src/test/java/seedu/tinner/logic/parser/CompanyListParserTest.java
Labels: bug, documentation

#291 Fix not able to view length of text
  src/main/java/seedu/tinner/ui/CompanyCard.java
  src/main/java/seedu/tinner/ui/RoleCard.java
Labels: bug

#292 Fix displaying max length of email
  src/main/java/seedu/tinner/ui/CompanyCard.java
Labels: bug

#296 Reduce default company list
  docs/UserGuide.md
  src/main/java/seedu/tinner/model/reminder/Reminder.java
  src/main/java/seedu/tinner/model/util/SampleDataUtil.java
  src/main/java/seedu/tinner/ui/HelpWindow.java
  src/main/resources/images/command_table.png
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: bug

#293 Update reminder sort logic
  docs/UserGuide.md
  src/main/java/seedu/tinner/model/reminder/Reminder.java
Labels: documentation, enhancement

#295 Update execution of commandResult
  docs/DeveloperGuide.md
  docs/diagrams/EditRoleActivityDiagram.puml
  docs/images/EditRoleActivityDiagram.png
Labels: documentation

#297 Create DG set reminder window use case
  docs/DeveloperGuide.md
Labels: documentation

#298 Update Peter's PPP
  docs/team/petermonky.md
Labels: documentation

#299 Update header for documentation
  docs/_sass/minima/_base.scss
Labels: documentation

#300 Update Peter's PPP community section
  docs/team/petermonky.md
Labels: documentation

#303 Update PPP
  docs/team/kerbysoh.md
Labels: documentation

#306 Update images and spacing for UG
  docs/UserGuide.md
  docs/images/AddCompanyDemo.png
  docs/images/AddRoleDemo.png
  docs/images/DeleteCompanyDemo.png
  docs/images/DeleteRoleDemo.png
  docs/images/EditCompanyDemo.png
  docs/images/EditRoleDemo.png
  docs/images/FavouriteDemo.png
  docs/images/FindCompanyDemo.png
  docs/images/FindRoleDemo.png
  docs/images/ReminderDemo.png
  docs/images/Ui.png
  docs/images/UnfavouriteDemo.png
  docs/images/WindowDemo.png
Labels: documentation

#307 Update DG UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/tinner/model/reminder/UniqueReminderList.java
Labels: documentation

#308 Update image size
  docs/UserGuide.md
  docs/images/Reminder.png
  docs/index.md
Labels: documentation

#309 Update Peter's PPP UG section
  docs/team/petermonky.md
Labels: documentation

#311 Fix find role demo image in UG
  docs/images/FindCompanyDemo.png
  docs/images/FindRoleDemo.png
Labels: documentation

#304 Create DG Find feature use case and manual testing for AddRole and DeleteRole
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#305 Update Find feature to include validity check
  src/main/java/seedu/tinner/logic/parser/FindCommandParser.java
  src/main/java/seedu/tinner/logic/parser/ParserUtil.java
Labels: enhancement

#301 Update DG effort (draft)
  docs/DeveloperGuide.md
Labels: documentation

#313 Fix UI class diagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: bug, documentation

#315 Add additional technical terminologies to UG
  docs/UserGuide.md
Labels: documentation

#319 Update personal PPP
  docs/team/jinnhl.md
Labels: documentation

#320 Update UG Demo use cases
  docs/UserGuide.md
Labels: documentation

#321 Update UG links
  docs/UserGuide.md
Labels: documentation
