Repository AY2122S2-CS2103T-T17-1/tp, pull requests merged in 2022-03, with the labels that each got.

#60 Update ParserUtilTest to handle parsing of 2 indexes
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: enhancement

#64 Update storage to read companies and roles from json file
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCompanyCommandParser.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/role/Role.java
  src/main/java/seedu/address/model/role/RoleManager.java
  src/main/java/seedu/address/model/role/RoleName.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCompany.java
  src/main/java/seedu/address/storage/JsonAdaptedRole.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCompanyCommandParserTest.java
  src/test/java/seedu/address/model/company/NameTest.java
  src/test/java/seedu/address/model/company/RoleNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/company/RoleNameTest.java
  src/test/java/seedu/address/model/role/RoleNameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/address/testutil/CompanyBuilder.java
  src/test/java/seedu/address/testutil/RoleBuilder.java
  src/test/java/seedu/address/testutil/TypicalCompanies.java
Labels: enhancement

#68 Format deadline before writing to JSON
  src/main/java/seedu/address/model/role/Role.java
  src/main/java/seedu/address/storage/JsonAdaptedRole.java
Labels: bug, enhancement

#71 Create DeleteRoleCommand and parser class
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteRoleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteRoleCommandParser.java
  src/main/java/seedu/address/model/role/RoleManager.java
  src/test/java/seedu/address/logic/commands/DeleteRoleCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteRoleCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalCompanies.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: enhancement

#72 Implement Role Tags to display roles tagged to each company
  src/main/java/seedu/address/model/role/RoleManager.java
  src/main/java/seedu/address/ui/CompanyCard.java
  src/main/resources/view/CompanyListCard.fxml
  src/main/resources/view/DarkTheme.css
Labels: enhancement

#80 Refactor Name to CompanyName
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/company/CompanyName.java
  src/main/java/seedu/address/model/company/CompanyNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCompany.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCompanyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CompanyListParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/company/CompanyNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/company/CompanyNameTest.java
  src/test/java/seedu/address/model/company/RoleNameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/address/testutil/CompanyBuilder.java
  src/test/java/seedu/address/testutil/EditCompanyDescriptorBuilder.java
Labels: enhancement

#83 Implement changes to UI for Role Fields
  src/main/java/seedu/address/ui/RoleCard.java
Labels: enhancement

#75 Create AddRoleCommand and parser class
  src/main/java/seedu/address/logic/commands/AddRoleCommand.java
  src/main/java/seedu/address/logic/parser/AddRoleCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/role/RoleManager.java
Labels: enhancement

#85 Update storage tests
  src/main/java/seedu/address/model/company/CompanyName.java
  src/main/java/seedu/address/model/role/RoleManager.java
  src/main/java/seedu/address/storage/JsonAdaptedRole.java
  src/test/data/JsonSerializableCompanyListTest/typicalCompaniesList.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCompanyDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCompanyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/CompanyListTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/company/CompanyTest.java
  src/test/java/seedu/address/model/company/UniqueCompanyListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRoleTest.java
  src/test/java/seedu/address/storage/JsonCompanyListStorageTest.java
  src/test/java/seedu/address/testutil/TypicalCompanies.java
Labels: testing

#101 Update User Guide
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: documentation

#100 Implement find command to search for roles
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/company/CompanyNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/role/RoleManager.java
  src/main/java/seedu/address/model/role/RoleNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/CompanyCard.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCompanyCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCompanyCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/CompanyListParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/company/CompanyNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/role/RoleNameContainsKeywordsPredicateTest.java
Labels: enhancement

#103 Update index.md
  docs/index.md
Labels: documentation

#105 Update tests for Find command and parser
  src/main/java/seedu/address/logic/commands/AddRoleCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/company/CompanyNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/role/Deadline.java
  src/main/java/seedu/address/model/role/Description.java
  src/main/java/seedu/address/model/role/RoleManager.java
  src/main/java/seedu/address/model/role/RoleNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/role/Stipend.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCompanyCommandTest.java
  src/test/java/seedu/address/logic/commands/AddRoleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCompanyCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddRoleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CompanyListParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/company/CompanyNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/role/DescriptionTest.java
  src/test/java/seedu/address/model/role/RoleNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/role/StipendTest.java
  src/test/java/seedu/address/testutil/RoleBuilder.java
  src/test/java/seedu/address/testutil/TypicalRoles.java
Labels: testing

#104 Revamp UI
  .github/check-line-endings.sh
  src/main/java/seedu/address/ui/CompanyCard.java
  src/main/resources/fonts/roboto_mono/LICENSE.txt
  src/main/resources/fonts/roboto_mono/README.txt
  src/main/resources/fonts/roboto_mono/RobotoMono-Italic-VariableFont_wght.ttf
  src/main/resources/fonts/roboto_mono/RobotoMono-VariableFont_wght.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-Bold.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-BoldItalic.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-ExtraLight.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-ExtraLightItalic.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-Italic.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-Light.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-LightItalic.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-Medium.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-MediumItalic.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-Regular.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-SemiBold.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-SemiBoldItalic.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-Thin.ttf
  src/main/resources/fonts/roboto_mono/static/RobotoMono-ThinItalic.ttf
  src/main/resources/fonts/rubik/OFL.txt
  src/main/resources/fonts/rubik/README.txt
  src/main/resources/fonts/rubik/Rubik-Italic-VariableFont_wght.ttf
  src/main/resources/fonts/rubik/Rubik-VariableFont_wght.ttf
  src/main/resources/fonts/rubik/static/Rubik-Black.ttf
  src/main/resources/fonts/rubik/static/Rubik-BlackItalic.ttf
  src/main/resources/fonts/rubik/static/Rubik-Bold.ttf
  src/main/resources/fonts/rubik/static/Rubik-BoldItalic.ttf
  src/main/resources/fonts/rubik/static/Rubik-ExtraBold.ttf
  src/main/resources/fonts/rubik/static/Rubik-ExtraBoldItalic.ttf
  src/main/resources/fonts/rubik/static/Rubik-Italic.ttf
  src/main/resources/fonts/rubik/static/Rubik-Light.ttf
  src/main/resources/fonts/rubik/static/Rubik-LightItalic.ttf
  src/main/resources/fonts/rubik/static/Rubik-Medium.ttf
  src/main/resources/fonts/rubik/static/Rubik-MediumItalic.ttf
  src/main/resources/fonts/rubik/static/Rubik-Regular.ttf
  src/main/resources/fonts/rubik/static/Rubik-SemiBold.ttf
  src/main/resources/fonts/rubik/static/Rubik-SemiBoldItalic.ttf
  src/main/resources/view/CompanyCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RoleListPanel.fxml
Labels: enhancement

#108 Fix edit command
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/address/logic/commands/AddRoleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRoleCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/CompanyList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyCompanyList.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/company/CompanyNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/company/ReadOnlyRoleList.java
  src/main/java/seedu/address/model/company/RoleList.java
  src/main/java/seedu/address/model/company/RoleManager.java
  src/main/java/seedu/address/model/company/UniqueCompanyList.java
  src/main/java/seedu/address/model/role/Deadline.java
  src/main/java/seedu/address/model/role/Description.java
  src/main/java/seedu/address/model/role/Role.java
  src/main/java/seedu/address/model/role/RoleManager.java
  src/main/java/seedu/address/model/role/RoleNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/role/Stipend.java
  src/main/java/seedu/address/model/role/UniqueRoleList.java
  src/main/java/seedu/address/model/role/exceptions/DuplicateRoleException.java
  src/main/java/seedu/address/model/role/exceptions/RoleNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCompany.java
  src/main/java/seedu/address/storage/JsonSerializableRoleList.java
  src/main/java/seedu/address/ui/CompanyCard.java
  src/main/java/seedu/address/ui/RoleListPanel.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCompanyCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCompanyCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteRoleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddRoleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CompanyListParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/CompanyListTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/company/CompanyNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/role/DescriptionTest.java
  src/test/java/seedu/address/model/role/StipendTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/address/testutil/CompanyBuilder.java
  src/test/java/seedu/address/testutil/CompanyUtil.java
  src/test/java/seedu/address/testutil/RoleBuilder.java
Labels: bug

#111 Minor UI change
  src/main/resources/view/DarkTheme.css
Labels: enhancement

#114 Fix storage behaviour with find command
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/company/CompanyNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/company/ReadOnlyRoleList.java
  src/main/java/seedu/address/model/company/RoleList.java
  src/main/java/seedu/address/model/company/RoleManager.java
  src/main/java/seedu/address/storage/JsonAdaptedCompany.java
  src/main/java/seedu/address/storage/JsonSerializableRoleList.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: bug

#112 Fix find command
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/company/CompanyNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/company/RoleManager.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: bug, enhancement

#106 Implement enhanced tests and assertion checks for the newly created Find Command
  src/main/java/seedu/address/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/company/CompanyNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/role/RoleNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddRoleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/CompanyListParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/company/CompanyNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/role/RoleNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/CompanyBuilder.java
Labels: testing

#117 Update Ui.png
  docs/images/Ui.png
Labels: documentation

#118 Create editRole command
  src/main/java/seedu/address/logic/commands/EditRoleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditRoleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/EditRoleCommandTest.java
  src/test/java/seedu/address/testutil/EditRoleDescriptorBuilder.java
Labels: enhancement

#120 Update test for EditRole feature
  src/main/java/seedu/address/logic/commands/EditRoleCommand.java
  src/main/java/seedu/address/logic/parser/EditRoleCommandParser.java
  src/test/java/seedu/address/logic/commands/EditRoleCommandTest.java
  src/test/java/seedu/address/logic/parser/EditRoleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: testing

#127 Update User Guide with the new Find Command details
  docs/UserGuide.md
Labels: documentation

#126 Update ParserUtilTest to include new method parseIndexWithContent
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: testing

#133 Update rolename comparison and to accept single pair of brackets
  src/main/java/seedu/tinner/logic/commands/AddRoleCommand.java
  src/main/java/seedu/tinner/model/role/Role.java
  src/main/java/seedu/tinner/model/role/RoleName.java
  src/test/java/seedu/tinner/model/role/RoleNameTest.java
  src/test/java/seedu/tinner/model/role/RoleTest.java
Labels: bug, enhancement

#139 Update UG for Edit commands
  docs/UserGuide.md
Labels: documentation

#142 Add star icon for favourite status
  src/main/java/seedu/tinner/logic/commands/FavouriteCompanyCommand.java
  src/main/java/seedu/tinner/logic/commands/UnfavouriteCompanyCommand.java
  src/main/java/seedu/tinner/model/company/CompanyHasBeenFavouritedPredicate.java
  src/main/java/seedu/tinner/model/company/FavouriteStatus.java
  src/main/java/seedu/tinner/ui/CompanyCard.java
  src/main/resources/images/star.png
  src/main/resources/view/CompanyCard.fxml
  src/test/java/seedu/tinner/logic/commands/CommandTestUtil.java
Labels: enhancement

#146 Update role commands to interact with model
  src/main/java/seedu/tinner/logic/commands/AddRoleCommand.java
  src/main/java/seedu/tinner/logic/commands/DeleteRoleCommand.java
  src/main/java/seedu/tinner/logic/commands/EditRoleCommand.java
  src/main/java/seedu/tinner/model/Model.java
  src/main/java/seedu/tinner/model/ModelManager.java
  src/test/java/seedu/tinner/logic/commands/AddCompanyCommandTest.java
  src/test/java/seedu/tinner/logic/commands/AddRoleCommandTest.java
  src/test/java/seedu/tinner/logic/commands/DeleteRoleCommandTest.java
  src/test/java/seedu/tinner/logic/commands/EditRoleCommandTest.java
  src/test/java/seedu/tinner/logic/parser/EditRoleCommandParserTest.java
Labels: enhancement

#143 Update Storage class to save FavouriteStatus field within each Company
  src/main/java/seedu/tinner/model/company/FavouriteStatus.java
  src/main/java/seedu/tinner/storage/JsonAdaptedCompany.java
  src/test/data/JsonSerializableCompanyListTest/duplicateCompanyList.json
  src/test/data/JsonSerializableCompanyListTest/typicalCompaniesList.json
  src/test/java/seedu/tinner/storage/JsonAdaptedCompanyTest.java
Labels: enhancement

#151 Update UI in DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: documentation

#152 Update DG Draft with Edit Role Implementation
  docs/DeveloperGuide.md
  docs/diagrams/EditRoleDiagram.puml
  docs/diagrams/EditRoleSeqeuenceDiagram.puml
  docs/diagrams/detailed.puml
  docs/images/EditRoleDiagram.png
  docs/images/EditRoleSequenceDiagram.png
Labels: documentation

#155 Update Developer Guide with Find feature implementation
  docs/DeveloperGuide.md
  docs/diagrams/EditRoleDiagram.puml
  docs/diagrams/FindDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindDiagram.png
  docs/images/FindSequenceDiagram.png
Labels: documentation

#158 Update Developer Guide with Logic component
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCompanySequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/DeleteCompanySequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
Labels: documentation

#165 Update Developer Guide with Delete Role feature
  docs/DeveloperGuide.md
  docs/diagrams/DeleteRoleDiagram.puml
  docs/diagrams/DeleteRoleSequenceDiagram.puml
  docs/diagrams/EditRoleSequenceDiagram.puml
  docs/images/DeleteRoleDiagram.png
  docs/images/DeleteRoleSequenceDiagram.png
  docs/images/EditRoleSequenceDiagram.png
Labels: documentation

#167 Implement Reminder Logic in Model
  src/main/java/seedu/tinner/MainApp.java
  src/main/java/seedu/tinner/model/CompanyList.java
  src/main/java/seedu/tinner/model/Model.java
  src/main/java/seedu/tinner/model/ModelManager.java
  src/main/java/seedu/tinner/model/ReadOnlyCompanyList.java
  src/main/java/seedu/tinner/model/reminder/Reminder.java
  src/main/java/seedu/tinner/model/reminder/UniqueReminderList.java
  src/main/java/seedu/tinner/model/role/Deadline.java
  src/main/java/seedu/tinner/storage/JsonAdaptedCompany.java
  src/main/java/seedu/tinner/storage/JsonAdaptedRole.java
Labels: enhancement

#169 Improve Reminder feature
  src/main/java/seedu/tinner/MainApp.java
  src/main/java/seedu/tinner/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/tinner/model/UserPrefs.java
  src/main/java/seedu/tinner/model/role/Deadline.java
  src/main/java/seedu/tinner/model/role/Role.java
  src/main/java/seedu/tinner/model/role/Status.java
  src/main/java/seedu/tinner/storage/JsonAdaptedCompany.java
Labels: enhancement

#166 Update DG Architecture and AddRole Implementation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddRoleDiagram.puml
  docs/diagrams/AddRoleSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/AddRoleDiagram.png
  docs/images/AddRoleSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/team/justinyjt.md
  docs/team/kerbysoh.md
Labels: documentation

#175 Creates SetReminderWindow Command and edits Reminder feature implementation
  src/main/java/seedu/tinner/commons/core/Messages.java
  src/main/java/seedu/tinner/logic/commands/AddCompanyCommand.java
  src/main/java/seedu/tinner/logic/commands/ClearCommand.java
  src/main/java/seedu/tinner/logic/commands/DeleteCompanyCommand.java
  src/main/java/seedu/tinner/logic/commands/EditCompanyCommand.java
  src/main/java/seedu/tinner/logic/commands/ExitCommand.java
  src/main/java/seedu/tinner/logic/commands/FavouriteCompanyCommand.java
  src/main/java/seedu/tinner/logic/commands/ListCommand.java
  src/main/java/seedu/tinner/logic/commands/ListFavouriteCommand.java
  src/main/java/seedu/tinner/logic/commands/SetReminderWindowCommand.java
  src/main/java/seedu/tinner/logic/commands/UnfavouriteCompanyCommand.java
  src/main/java/seedu/tinner/logic/parser/CompanyListParser.java
  src/main/java/seedu/tinner/logic/parser/SetReminderWindowCommandParser.java
  src/main/java/seedu/tinner/model/Model.java
  src/main/java/seedu/tinner/model/ModelManager.java
  src/main/java/seedu/tinner/model/ReadOnlyCompanyList.java
  src/main/java/seedu/tinner/model/company/Address.java
  src/main/java/seedu/tinner/model/company/CompanyName.java
  src/main/java/seedu/tinner/model/company/Email.java
  src/main/java/seedu/tinner/model/company/FavouriteStatus.java
  src/main/java/seedu/tinner/model/company/Phone.java
  src/main/java/seedu/tinner/model/company/RoleManager.java
  src/main/java/seedu/tinner/model/reminder/Reminder.java
  src/main/java/seedu/tinner/model/reminder/UniqueReminderList.java
  src/main/java/seedu/tinner/model/role/Description.java
  src/main/java/seedu/tinner/model/role/Role.java
  src/main/java/seedu/tinner/model/role/UniqueRoleList.java
  src/main/java/seedu/tinner/storage/JsonAdaptedRole.java
  src/test/java/seedu/tinner/logic/commands/AddCompanyCommandTest.java
  src/test/java/seedu/tinner/logic/commands/AddRoleCommandTest.java
  src/test/java/seedu/tinner/logic/commands/SetReminderWindowCommandTest.java
  src/test/java/seedu/tinner/logic/parser/SetReminderWindowCommandParserTest.java
Labels: documentation, enhancement

#174 Update colour-coding of tags
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/tinner/model/ModelManager.java
  src/main/java/seedu/tinner/ui/CompanyCard.java
  src/main/resources/view/DarkTheme.css
Labels: documentation, enhancement

#177 Update Reminder class to include a Status field
  src/main/java/seedu/tinner/model/ModelManager.java
  src/main/java/seedu/tinner/model/reminder/Reminder.java
  src/main/java/seedu/tinner/storage/JsonAdaptedCompany.java
  src/test/java/seedu/tinner/logic/LogicManagerTest.java
  src/test/java/seedu/tinner/logic/commands/AddCompanyCommandIntegrationTest.java
  src/test/java/seedu/tinner/logic/commands/ClearCommandTest.java
  src/test/java/seedu/tinner/logic/commands/DeleteCompanyCommandTest.java
  src/test/java/seedu/tinner/logic/commands/DeleteRoleCommandTest.java
  src/test/java/seedu/tinner/logic/commands/EditCompanyCommandTest.java
  src/test/java/seedu/tinner/logic/commands/EditRoleCommandTest.java
  src/test/java/seedu/tinner/logic/commands/FavouriteCompanyCommandTest.java
  src/test/java/seedu/tinner/logic/commands/FindCommandTest.java
  src/test/java/seedu/tinner/logic/commands/ListCommandTest.java
  src/test/java/seedu/tinner/logic/commands/ListFavouriteCommandTest.java
  src/test/java/seedu/tinner/logic/commands/SetReminderWindowCommandTest.java
  src/test/java/seedu/tinner/logic/commands/UnfavouriteCompanyCommandTest.java
  src/test/java/seedu/tinner/model/ModelManagerTest.java
Labels: enhancement

#179 Create Reminder UI
  src/main/java/seedu/tinner/MainApp.java
  src/main/java/seedu/tinner/logic/Logic.java
  src/main/java/seedu/tinner/model/Model.java
  src/main/java/seedu/tinner/model/ModelManager.java
  src/main/java/seedu/tinner/model/company/CompanyName.java
  src/main/java/seedu/tinner/model/company/CompanyNameContainsKeywordsPredicate.java
  src/main/java/seedu/tinner/model/reminder/Reminder.java
  src/main/java/seedu/tinner/model/reminder/UniqueReminderList.java
  src/main/java/seedu/tinner/model/role/RoleName.java
  src/main/java/seedu/tinner/model/role/RoleNameContainsKeywordsPredicate.java
  src/main/java/seedu/tinner/storage/JsonAdaptedCompany.java
  src/main/java/seedu/tinner/ui/CompanyCard.java
  src/main/java/seedu/tinner/ui/MainWindow.java
  src/main/java/seedu/tinner/ui/ReminderCard.java
  src/main/java/seedu/tinner/ui/ReminderDateCard.java
  src/main/java/seedu/tinner/ui/ReminderDateListPanel.java
  src/main/java/seedu/tinner/ui/ReminderListPanel.java
  src/main/java/seedu/tinner/ui/ReminderWindow.java
  src/main/java/seedu/tinner/ui/RoleCard.java
  src/main/java/seedu/tinner/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ReminderCard.fxml
  src/main/resources/view/ReminderDateCard.fxml
  src/main/resources/view/ReminderDateListPanel.fxml
  src/main/resources/view/ReminderListPanel.fxml
  src/main/resources/view/ReminderWindow.fxml
  src/main/resources/view/RoleListPanel.fxml
  src/test/java/seedu/tinner/logic/LogicManagerTest.java
  src/test/java/seedu/tinner/logic/commands/AddCompanyCommandIntegrationTest.java
  src/test/java/seedu/tinner/logic/commands/ClearCommandTest.java
  src/test/java/seedu/tinner/logic/commands/CommandTestUtil.java
  src/test/java/seedu/tinner/logic/commands/DeleteCompanyCommandTest.java
  src/test/java/seedu/tinner/logic/commands/DeleteRoleCommandTest.java
  src/test/java/seedu/tinner/logic/commands/EditCompanyCommandTest.java
  src/test/java/seedu/tinner/logic/commands/EditRoleCommandTest.java
  src/test/java/seedu/tinner/logic/commands/FavouriteCompanyCommandTest.java
  src/test/java/seedu/tinner/logic/commands/FindCommandTest.java
  src/test/java/seedu/tinner/logic/commands/ListCommandTest.java
  src/test/java/seedu/tinner/logic/commands/ListFavouriteCommandTest.java
  src/test/java/seedu/tinner/logic/commands/SetReminderWindowCommandTest.java
  src/test/java/seedu/tinner/logic/commands/UnfavouriteCompanyCommandTest.java
  src/test/java/seedu/tinner/model/ModelManagerTest.java
  src/test/java/seedu/tinner/testutil/CompanyUtil.java
Labels: enhancement

#183 Update UserGuide to include SetReminderWindow Command
  docs/UserGuide.md
Labels: documentation

#186 Improve Reminder UI
  src/main/java/seedu/tinner/ui/ReminderCard.java
  src/main/java/seedu/tinner/ui/ReminderDateCard.java
  src/main/java/seedu/tinner/ui/ReminderDateListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ReminderCard.fxml
  src/main/resources/view/ReminderDateListPanel.fxml
Labels: enhancement

#185 Update User Guide and Testing
  docs/UserGuide.md
  src/test/java/seedu/tinner/model/role/RoleManagerTest.java
  src/test/java/seedu/tinner/storage/JsonAdaptedRoleTest.java
Labels: documentation, testing

#190 Update index.md
  docs/images/Reminder.png
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/tinner/ui/UiManager.java
  src/main/resources/images/tinner.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/tinner/commons/util/AppUtilTest.java
Labels: documentation

#192 Fix index.md
  docs/index.md
Labels: bug, documentation

#194 Updates UG to include demo use cases
  docs/UserGuide.md
  docs/images/AddCompanyDemo.png
  docs/images/AddRoleDemo.png
  docs/images/DeleteCompanyDemo.png
  docs/images/DeleteRoleDemo.png
Labels: documentation

#191 Implement testing for Reminder feature
  docs/UserGuide.md
  src/main/java/seedu/tinner/model/reminder/Reminder.java
  src/main/java/seedu/tinner/model/reminder/exceptions/DuplicateReminderException.java
  src/test/java/seedu/tinner/logic/commands/CommandTestUtil.java
  src/test/java/seedu/tinner/model/reminder/ReminderTest.java
  src/test/java/seedu/tinner/model/reminder/UniqueReminderListTest.java
  src/test/java/seedu/tinner/testutil/ReminderBuilder.java
  src/test/java/seedu/tinner/testutil/TypicalReminders.java
Labels: testing

#197 Update User Guide with Command Restrictions and FAQs
  docs/UserGuide.md
Labels: documentation
